name: angular_maps
dependencies:
  google_maps: ^3.1.0
  angular2: "2.0.0-beta.22"
dependency_overrides:
  source_gen: ^0.5.1
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/index.dart